### ISSUE TITLE
2018/09/04 TODO

### ISSUE THREAD

**Issue by hatiparallel** [line-school2018summer/tokyo-c-server#18]
基本的にクライアントの通信はサーバ、UIができてから。
それ以外は順番どうでもいいけど、何となく上からのイメージ。
ここにあるのはほとんど、1度以上話題に上がった必須のこと。たまに「やれたらいいな」も混じっている。
数は多いけど（特にクライアントは）細分化しているので、9/13までにほとんどここのことは終わっているといいなあ（超希望的観測）
漏れあったらごめんなさい。ありそう。

**【サーバ】**

- [x] 1. グループ参加からグループ招待へのエンドポイント変更
- [x] 2. PIN発行のエンドポイント追加
- [x] 3. 友達登録のエンドポイントをPIN用に変更
- [x] 4. ユーザーごとの新規メッセージ、友達の通知のエンドポイント作成
- [x] 5. isEventメッセージ（グループ参加、グループ退会）のサーバでの作成

**【クライアント】**

- [x] 1. グループのrealm化
- [x] 2. 個人間、グループ間のトークルームの統合とそれに伴う画面遷移、型等の変更
- [x] 3. グループ退会のUI追加
- [x] 4. グループ退会の通信追加
- [x] 5. 友達削除の通信追加
- [x] 6. グループ招待のUI追加
- [x] 7. グループ参加からグループ招待への変更
- [x] 8. PIN発行のUI追加
- [x] 9. PIN発行の通信追加
- [x] 10. 友達登録の通信追加
- [x] 11. PIN発行画面のストリーミング受信の通信追加
- [x] 12. バックグラウンドでのポーリング受信処理の実装
- [x] 13. バックグラウンドでの受信のユーザーへの通知の実装（プッシュ通知）
- [x] 14. MessageActivity起動時のsince_idによるメッセージの取得
- [x] 15. MessageActivity起動時のsince_idによるメッセージのrealmへの保存
- [x] 16. isEventメッセージの処理：グループ参加/退会
- [x] 17. グループメンバー一覧のUI
- [x] 18. グループメンバー一覧におけるrealmのMemberからの検索表示
- [x] 19. グループメンバー一覧のうちrealmにないものの通信での取得
- [x] 20. firebaseでのプロフィール画像の保存
- [x] 21. 他人の情報（名前、プロフィール画像）の定期的な更新
